export const restaurantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "588891",
        name: "The Pizza Bunker",
        uuid: "17a806bc-d406-4fb8-86fc-5e0a4c515a1c",
        city: "47",
        area: "New Amar Nagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "wnteh4cpcctz7needphz",
        cuisines: ["Pizzas", "Italian", "Fast Food"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0.800000011920929,
        slugs: {
          restaurant: "the-pizza-bunker-north_jalandhar-north_jalandhar",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "Shaheed babu labh singh nagar Gali no 10, near, Durga Mandir Rd, New Amar Nagar, Jalandhar, Punjab 144001, India",
        locality: "Shaheed Babu Labh Singh Nagar",
        parentId: 352272,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "588891",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0.800000011920929,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "112607",
        name: "New Aar Kay Vaishno Dhaba (Kapurthala Road)",
        uuid: "1dfaa9d0-3b54-410b-a1f0-1712e3c3171a",
        city: "47",
        area: "Basti Bawa Khel",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "hrjpqey3zgbkhvn0ajba",
        cuisines: ["North Indian", "Chinese", "Thalis"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "aar-kay-vaishno-dhaba-basti-bawa-khel-jalandhar_central",
          city: "jalandhar",
        },
        cityState: "47",
        address: "kapurthala road near surgical complex basti bawa khel",
        locality: "Kapurthala Road",
        parentId: 145670,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "112607",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "347917",
        name: "KFC",
        uuid: "55717eec-669d-4b3e-b2f4-5a8d103360cb",
        city: "47",
        area: "Shastri Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 5.900000095367432,
        slugs: {
          restaurant: "kfc-mkc-mall-south_jalandhar",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "KFC Restaurant, MKC mall shop no- 1 , new jawahar nagar jalandhar - 144001",
        locality: "Mahavir Marg",
        parentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7116663~p=4~eid=00000188-dc95-7bc8-04e9-40a8000f0475~srvts=1687327964104",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "347917",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 5.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "349175",
        name: "Pizza Roberto",
        uuid: "1c70f216-b943-4d2d-852f-88e66bdd2684",
        city: "47",
        area: "Adarsh Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "b5pzn1fayfuqklftrjfi",
        cuisines: [
          "Continental",
          "Italian",
          "Pizzas",
          "American",
          "Beverages",
          "Chinese",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "pizza-roberto-north_jalandhar-north_jalandhar",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "Gali No. 10, Shaheed Babu Labh Singh Nagar, Jalandhar., Jalandhar-1 (P/S 1,2,3,4,5, Sub Division Jalandhar-1), Jalandhar, Punjab",
        locality: "Babu Labh Singh Nagar",
        parentId: 158916,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "349175",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "98907",
        name: "Maddi Refreshments",
        uuid: "ad3ef067-50d3-494f-9e45-136408887ed3",
        city: "47",
        area: "Burlton Park",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "eabespjc5tudmnjedl5b",
        cuisines: ["Snacks", "North Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2.0999999046325684,
        slugs: {
          restaurant: "maddi-refreshments-shastri-nagar-jalandhar_central",
          city: "jalandhar",
        },
        cityState: "47",
        address: "Shop 3, Main Road, Kabir Nagar, Shastri Nagar, Jalandhar",
        locality: "Kabir Nagar",
        parentId: 128425,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "98907",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2.0999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.5",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "283810",
        name: "Yummy Delicious Till Last Bite",
        uuid: "5ba943fb-b9d1-4996-8aa6-6a5f769b6960",
        city: "47",
        area: "Model Town",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "wwgslew60sfsdtfy2ijz",
        cuisines: ["Chinese", "Continental", "Italian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        slaString: "44 MINS",
        lastMileTravel: 6,
        slugs: {
          restaurant:
            "yummy-delicious-till-last-bite-jalandhar_central-jalandhar_central",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "Shop No. 6, G.T.B. Opp. Ghai Hospital, GTB Nagar, Jalandhar, Punjab",
        locality: "Guru Teg Bahadur Nagar",
        parentId: 228634,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4200,
          message: "",
          title: "Delivery Charge",
          amount: "4200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7131316~p=7~eid=00000188-dc95-7bc8-04e9-40a9000f0754~srvts=1687327964104",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹175 OFF",
          subHeader: "ABOVE ₹400",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "283810",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          lastMileTravel: 6,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "382596",
        name: "The fusion bite",
        uuid: "589dc65f-7260-47cf-9239-86cc162426dc",
        city: "47",
        area: "Adarsh Nagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "fx1ctjkuumq2wnkqigot",
        cuisines: [
          "Pizzas",
          "Italian-American",
          "Chinese",
          "Beverages",
          "Snacks",
        ],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0.8999999761581421,
        slugs: {
          restaurant: "the-fusion-bite-north_jalandhar-north_jalandhar",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "Gali No. 10, Shaheed Babu Labh Singh Nagar, Jalandhar., Jalandhar-1 (P/S 1,2,3,4,5, Sub Division Jalandhar-1), Jalandhar, , Punjab, 144001",
        locality: "Shaheed Babu Labh Singh Nagar",
        parentId: 257498,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "382596",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0.8999999761581421,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "263164",
        name: "Hari Burger",
        uuid: "083aa264-1b3e-4f14-aa17-0f578631b1ab",
        city: "47",
        area: "North_Jalandhar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ynarnd0haqjsbgrzeasx",
        cuisines: ["Burgers", "Chinese", "Pizzas", "Pastas", "Italian-American"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "hari-burger-jalandhar_central-jalandhar_central",
          city: "jalandhar",
        },
        cityState: "47",
        address: "8 Dilbag Nagar, Jalandhar,144001",
        locality: "Dilbagh Nagar",
        parentId: 21810,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "263164",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "664191",
        name: " Kanha Sweets (Amritsar Waale)",
        uuid: "8cb44ab4-b35d-4ca2-897c-deb7c64f3230",
        city: "47",
        area: "Urban Estate",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "690ec62bf8cab8de783622ac0b98cdb3",
        cuisines: ["Sweets", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 7.800000190734863,
        slugs: {
          restaurant: "kanha-sweets-south_jalandhar-south_jalandhar",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "Kanha Sweets , Police Station 1, Jalandhar-1 (P/S 1,2,3,4,5, Sub Division Jalandhar-1), Jalandhar, Punjab, 144022",
        locality: "Phase 2",
        parentId: 114617,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4200,
          message: "",
          title: "Delivery Charge",
          amount: "4200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7022465~p=10~eid=00000188-dc95-7bc8-04e9-40aa000f0a13~srvts=1687327964104",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "664191",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 7.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "285860",
        name: "Nanak Vegetarian Dhaba",
        uuid: "f672e7a5-dc87-4e0e-8d05-11038cd3166d",
        city: "47",
        area: "Harnam Daspura",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "usllk61gnicqmykbiyrb",
        cuisines: ["North Indian", "South Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "nanak-veg-dhaba-jalandhar_central-jalandhar_central",
          city: "jalandhar",
        },
        cityState: "47",
        address:
          "46, Kapurthala Road, Near Patel Chowk, Transport Nagar, Harnam Daspura, Jalandhar, Punjab , India",
        locality: "Transport Nagar",
        parentId: 143799,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 1900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "285860",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
  ];


export const IMG_CND_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
